services:
  - type: web
    name: glam-studios
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
